### DISCUSSION TITLE
Clusterfile v2

### DISCUSSION THREAD

**Discussion by fanux** [sealerio/sealer#837] [Announcements]
```
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8
  env:
    key: value
  ssh:
    passwd:
    pk: xxx
    pkPasswd: xxx
    user: root
  network:
    podCIDR: 100.64.0.0/10
    svcCIDR: 10.96.0.0/22
  certSANS:
    - aliyun-inc.com
    - 10.0.0.2
  hosts:
    - ip: 192.168.0.2
       role: master
       port: 2222
       ssh:
          user: xxx
          passwd: xxx
    - ip: 192.168.0.3
       role: node
```
1. delete provider field, using infra object instread.
2. add env field
3. modify hosts field

**Comment by fanux** [comment]
```
role: master 

role: [master, db]
```

**Comment by fanux** [comment]
```
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8
  env:
    key: value
  ssh:
    passwd:
    pk: xxx
    pkPasswd: xxx
    user: root
    port: 2222
  hosts:
    - ip: 192.168.0.2
       role: master
       ssh:
          user: xxx
          passwd: xxx
          port: 2222
    - ip: 192.168.0.3
       role: node
```

Also we can delete network and certConfig from Clusterfile.
