### ISSUE TITLE
remove duplicate ip cert sans

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1343]
#### What happened:

![image](https://user-images.githubusercontent.com/83740799/165491137-2a26cdeb-2e88-4e0c-bf10-9e226f1c62f1.png)

```yaml
apiServer:
  certSANs:
  - 127.0.0.1
  - apiserver.cluster.local
  - 10.103.97.2
  - 172.16.0.7
  - 127.0.0.1
  - apiserver.cluster.local
  - 10.103.97.2
  - 172.16.0.181
  extraArgs:
```

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
