### ISSUE TITLE
Kubfile导入离线镜像之后，还需要去下载docker 镜像

### ISSUE THREAD

**Issue by laowenyi** [sealerio/sealer#1397]
## Issue Description
我们想离线交付的时候，去掉中央hub仓库，然后把镜像打到我们定制的sealer image 里
文件系统如下
Kubefile
nginx
 -- nginx.yaml
nginx.tar
Kubefile如下
```
FROM kubernetes:v1.23.0
COPY nginx.tar images
COPY nginx manifests
CMD kubectl apply -f manifests/nginx/nginx.yaml

```

yaml 如下
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image:  nginx:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - name: http
      port: 82
      targetPort: 8000
  selector:
    app: nginx
  type: ClusterIP

```
执行 sealer build -f Kubfile -t xdr-nginx:1.0.1 --base=false . 报错
他还是要去拉镜像
init registry error: create proxy registry error: Get "http://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:33049->[::1]:53: read: connection refused

版本号
sealer v0.8.5
docker 
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275
 Built:             Tue Dec  1 19:14:24 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.14-sealer
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       711cc111cf
  Built:            Wed Jun  2 09:07:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
