### ISSUE TITLE
Clusterfile docker registry configuration

### ISSUE THREAD

**Issue by laotoutou** [sealerio/sealer#1400]
#### What happened:

I use the Clusterfile install kubernetes, the Clusterfile overrite registry custom domain, port, username and password:

```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: devops
spec:
  image: xxx
  ssh:
    pk: /root/.ssh/id_rsa
  hosts:
    - ips: [ 10.0.0.57 ]
      roles: [ master ]
    - ips: [ 10.0.0.63 ]
      roles: [ node ]
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: registry_passwd
spec:
  path: etc/registry.yml
  data: |
    domain: sea.hub
    port: "5000"
    username: name
    password: passwd
``` 

and run the command: `sealer apply -f Clusterfile`

then:

```
# kubectl -n kube-system get pods
NAME                               READY   STATUS              RESTARTS   AGE
coredns-55bcc669d7-fb57d           0/1     Pending             0          11m
coredns-55bcc669d7-mgsx2           0/1     Pending             0          11m
etcd-jone-all                      1/1     Running             0          11m
kube-apiserver-jone-all            1/1     Running             0          11m
kube-controller-manager-jone-all   1/1     Running             0          11m
kube-lvscare-guoyunyun-zhongqi     0/1     ContainerCreating   0          10m
kube-proxy-dj649                   1/1     Running             0          11m
kube-proxy-ff2dj                   0/1     ContainerCreating   0          11m
kube-scheduler-jone-all            1/1     Running             0          11m
```

```
[root@jone-all ~]# kubectl -n kube-system describe pod kube-proxy-ff2dj

......
Events:
  Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Normal   Scheduled               13m                default-scheduler  Successfully assigned kube-system/kube-proxy-ff2dj to guoyunyun-zhongqi
  Warning  FailedCreatePodSandBox  3m (x46 over 13m)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "sea.hub:5000/pause:3.2": Error response from daemon: Get https://sea.hub:5000/v2/pause/manifests/3.2: no basic auth credentials
```

#### What you expected to happen:

pod can successful pull the image from sea.hub:5000

#### Environment:

- sealer version (use `sealer version`): 
{"gitVersion":"v0.7.0","gitCommit":"a48bd32","buildDate":"2022-03-03 08:55:37","goVersion":"go1.16.14","compiler":"gc","platform":"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
