### ISSUE TITLE
optimization: image spec structure

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1450]
## Issue Description

Type: *feature request*

1. Support users to specify whether to download the container image. The default is true. If not , the build process will be very fast. and it is suitable for launching CloudImage in a networked environment.
 
2. The container image data is separated from the build context and exists in the local image storage system as `registry.tar.gz`.
 
new image spec structure:

```yaml
- kind: Image
  metadata:
    annotations:
      sea.aliyun.com/ClusterFile: ""
    creationTimestamp: null
    name: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8-alpine
  spec:
    id: 3de6a23e655a1a6bc683828de2303844c49681c18e7dc410bc569a284e7c8ab0
    image_config:
      args: {}
      cmd: {}
    mediators:
      - id: sha256:bdfff9613bacbb57f7d28210919f3ccbaba73e4042d080033ab4dc44dff9a274
        type: registry
      - id: sha256:b66e77105fb0a6350a5dc6818dd5dbc2ea94435e339577a533bff05aef7626e3
        type: registry
    layers:
      - id: sha256:ebd0f721b47d5f7f3ea287fe0882613960deef376e5556b34baab95330aa6bad
        type: COPY
        value: rootfs/* .
      - id: sha256:1066d30573cf0f2ae4c8ddc2cbe24c989ea5407ad5c72a8648902dd0d737c074
        type: COPY
        value: ${ARCH}/* .
      - id: sha256:6af04e85d342bdf7188ce0b44bdb1879ca2720a4c028b45daab81210c08b5fb2
        type: COPY
        value: imageList manifests
    platform:
      architecture: amd64
      os: linux
    sealer_version: v0.8.4
  status: {}
```
