### ISSUE TITLE
support to proxy image without cache in registry

### ISSUE THREAD

**Issue by yj-cloud** [sealerio/sealer#1478]
## Issue Description

Type: *feature request*

The directory of registry uses more and more storage when the cluster pulls image from the other registry frequently，and it's difficult to delete the images which is not need to cache.

### Describe what feature you want
Maybe supporting to proxy image without cache in registry is a idea to solve it. The registry only caches the images from the sealer's  cluster image.

### Additional context
**The codes of registry are not raw codes in sealer，could we open the registry codes in `sealerio` group？**

**Comment by justadogistaken** [comment]
@yj-cloud Do you mean that the sealer registry would cache all images even after the cluster is up by default? And we don't need to cache those new images duting cluster runtime, am I right?

**Comment by justadogistaken** [comment]
@yj-cloud Check [this](https://github.com/sealerio/sealer/blob/main/docs/design/docker-image-cache.md) out, you can turn it off with the following configration manually currently. We are planning to re-design the image-cache function.
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
#proxy:
# on: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
