### ISSUE TITLE
merge config did not take effect

### ISSUE THREAD

**Issue by sfeng1996** [sealerio/sealer#1482]
#### What happened:

i want to use sealer config to update network interface IP discovery rule，but not effective
this is my config clusterfile
```
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  creationTimestamp: null
  name: nodeAddr
spec:
  data: |
    spec:
      calicoNetwork:
        nodeAddressAutodetectionV4:
          interface: "eth.*|en.*|wlp.*|bond.*"
  path: etc/custom-resources.yaml
  strategy: merge
status: {}

```

this is  "etc/custom-resources.yaml"  after sealer apply
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: 100.64.0.0/10
      encapsulation: VXLAN
      natOutgoing: Enabled
      nodeSelector: all()
  registry: sea.hub:5000

---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}

```

i guess 'etc/custom-resource.yaml' have not key of 'nodeAddressAutodetectionV4:\n    interface:'  ， so sealer deepMerge config did not take effect

#### Environment:

- sealer version (use `sealer version`):  v0.8.5
-  kubernetes image: v1.21.12

**Comment by bxy4543** [comment]
Merge is only suitable for merging existing structures, and there are too many uncertainties for attributes that do not exist in this way, such as：
```config
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  creationTimestamp: null
  name: nodeAddr
spec:
  data: |
    spec:
      calicoNetwork:
        nodeAddressAutodetectionV4:
          interface: "eth.*|en.*|wlp.*|bond.*"
  path: etc/custom-resources.yaml
  strategy: merge
status: {}
```
result:
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      interface: "eth.*|en.*|wlp.*|bond.*"
    ipPools:
    - blockSize: 26
      cidr: 100.64.0.0/10
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
  registry: sea.hub:5000

---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: 
  calicoNetwork:
  nodeAddressAutodetectionV4:
    interface: "eth.*|en.*|wlp.*|bond.*"
```

The properties of APIServer are also merged in, so I think merge strategy is more suitable for merging of already existing properties.
