### ISSUE TITLE
I want to change the cidr，according the doc, but it does not affect

### ISSUE THREAD

**Issue by xwc1125** [sealerio/sealer#1493]
#### What happened:

I want to change the default cidr `100.64.0.0/10` to `10.64.0.0/10`. Then exec the `sealer apply -f Clusterfile` command,but it does not affect. 

#### What you expected to happen:
the cidr change，and ip change

#### How to reproduce it (as minimally and precisely as possible):
**First metod:**
1. `sealer run kubernetes:v1.19.8  ...`
2. change the Clusterfile

```yaml
metadata:
  annotations:
    ClusterfileName: /root/.sealer/Clusterfile
  creationTimestamp: null
  name: my-cluster
spec:
  hosts:
...
status: {}
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: calico
spec:
  path: etc/custom-resources.yaml
  strategy: merge
  data: |
    apiVersion: operator.tigera.io/v1
    kind: Installation
    metadata:
      name: default
    spec:
      calicoNetwork:
        ipPools:
        - blockSize: 26
          cidr: 10.64.0.0/10 #需与kubeadm配置中cidr一致
          encapsulation: VXLANCrossSubnet
          natOutgoing: Enabled
          nodeSelector: all()
```
3. sealer apply -f Clusterfile
4. 
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/4408289/172975635-10fb9570-17e1-4274-b615-1f25b2c75d34.png">

**Second metod:**
1. make `kubeadm.yml`:

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.19.8
networking:
  # dnsDomain: cluster.local
  podSubnet: 10.64.0.0/10
  serviceSubnet: 10.96.0.0/22
```
2. make `custom-resources.yaml`:

```yaml
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/v3.22/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  registry: sea.hub:5000
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 10.64.0.0/10
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()

---

# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/v3.22/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
```
3. make `Kubefile`:

```
#Kubefile
FROM kubernetes:v1.19.8
COPY kubeadm.yml etc
COPY custom-resources.yaml etc
```
4. `sealer build -t xwc1125-kubeadm-kubernetes:v1.19.8 .`
5.  `sealer run xwc1125-kubeadm-kubernetes:v1.19.8  ...`
6.  err:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/4408289/172976209-4e909d1f-7d43-4b62-9ea9-676c8575a1c5.png">

**Comment by xwc1125** [comment]
> 

{"gitVersion":"v0.8.5","gitCommit":"f9c3d99","buildDate":"2022-04-28 14:16:58","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

**Comment by bxy4543** [comment]
The default configuration image repository is incorrect, you can add in kubeadm.yml:

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.19.8
imageRepository: sea.hub:5000
networking:
  # dnsDomain: cluster.local
  podSubnet: 10.64.0.0/10
  serviceSubnet: 10.96.0.0/22
```
