### ISSUE TITLE
The Plugin LABEL and TAINT does not work

### ISSUE THREAD

**Issue by jackk01** [sealerio/sealer#1534]
```
sealer version
{"gitVersion":"v0.8.5","gitCommit":"f9c3d99","buildDate":"2022-04-28 14:16:58","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}
```

My Clusterfile:
```
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: MyLabel
spec:
  type: LABEL
  action: PostInstall
  data: |
    172.16.21.33 node-role.kubernetes.io/worker=

---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: taint
spec:
  type: TAINT
  action: PreGuest
  data: |
    172.16.21.30 node-role.kubernetes.io/master:NoSchedule-
    172.16.21.31 node-role.kubernetes.io/master:NoSchedule-
    172.16.21.32 node-role.kubernetes.io/master:NoSchedule-
```
