### ISSUE TITLE
[Proposal] separate env render function with two different instructions 

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1585]
## Issue Description

Currently , we use `env` at Clusterfile to render both basefs files and the environment variables for the shell to run scripts which bring more complexity and more difficult to understand for end user. Introduction form the official website : https://github.com/sealerio/sealer.cool/blob/main/src/docs/getting-started/using-clusterfile.md#env-render-support

And if the user has multiple fields that need to be modified at the same time, there will be potential problems using just one key from env render setting.

Therefore, I thought we can separate two functions with two Clusterfile instruction. one is setting the environment variables for the shell to run. One is used for rendering basefs .tmpl files.

Type: *feature request*

**Comment by kakaZhou719** [comment]
i thought , for rendering basefs .tmpl files:  We can migrate it to the config module. 

if the path is existed, use `render`, if not use `dump`.

```yaml
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: kubeadm-config
spec:
  path: etc/kubeadm.yml
  data: |
    PodSubnet: 100.64.0.0/10
    ServiceSubnet: 10.96.0.0/22
```
