### ISSUE TITLE
sealer cert --alt-names will only update cert of the first master node

### ISSUE THREAD

**Issue by hhyasdf** [sealerio/sealer#1608]
### What happen?

I have three master nodes in ClusterFile:
```yaml
...
  hosts:
    - ips:
        - 2408:4005:3d9:75a6:e239:14b3:f172:9758
        - 2408:4005:3d9:75a6:e239:14b3:f172:9756
        - 2408:4005:3d9:75a6:e239:14b3:f172:975a
      roles: [ master ] # add role field to specify the node role
    - ips:
        - 2408:4005:3d9:75a6:e239:14b3:f172:9757
        - 2408:4005:3d9:75a6:e239:14b3:f172:975b
        - 2408:4005:3d9:75a6:e239:14b3:f172:9759
      roles: [ node ]
```
Once I run `sealer cert --alt-names 10.0.255.35` on node "2408:4005:3d9:75a6:e239:14b3:f172:9758", the "10.0.255.35" ip address will only update into the cert of node "2408:4005:3d9:75a6:e239:14b3:f172:9758" itself, but the certs of another two master nodes is not updated, which is not expected.

### What you expected to happen?

The command of `sealer cert --alt-names` need to update all master nodes at the same time, or it's meaningless in production.

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others: 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-aliyun.1", GitCommit:"40ad569", GitTreeState:"", BuildDate:"2021-06-28T04:01:44Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-aliyun.1", GitCommit:"792b9c9", GitTreeState:"", BuildDate:"2021-07-19T10:33:37Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
