### ISSUE TITLE
[Feature] Support custom annotations and labels for selaer images

### ISSUE THREAD

**Issue by Starnop** [sealerio/sealer#1612]
## Issue Description

Type: *feature request*

### Describe what feature you want

Now, a sealer image contains a fixed annotations key `sea.aliyun.com/ClusterFile` 

```
# ./sealer inspect cloud-image-registry.cn-shanghai.cr.aliyuncs.com/foundations/adp-base:adp-1.5.0-alpha.1-8c090ff-12e6e1
- kind: Image
  metadata:
    annotations:
      sea.aliyun.com/ClusterFile: |
        apiVersion: sealer.cloud/v2
        kind: Cluster
        metadata:
          creationTimestamp: null
          name: my-cluster
        spec:
          image: xxx
          ssh:
            port: "22"
            user: root
        status: {}
    creationTimestamp: null
    name: xxx
  spec:
    id: d897134ef71e191cdfcc12ccf32dded2d7bc60f708832ad3302d9c85ec4fba79
......
```

In some cases, we need add some custom description information to the image. In addition, the [OCI specification](https://github.com/opencontainers/image-spec/blob/main/annotations.md) also had a definition for this problem.
