### ISSUE TITLE
Failed to deploy k8s cluster on WSL2 

### ISSUE THREAD

**Issue by xiaozitwo** [sealerio/sealer#1666]
### What happen?

[root@remote sealer]# ./sealer apply -f ./Clusterfile.yaml 
Usage:
  sealer apply [flags]

Examples:
sealer apply -f Clusterfile

Flags:
  -f, --Clusterfile string   Clusterfile path to apply a Kubernetes cluster (default "Clusterfile")
      --force                force to delete the specified cluster if set true
  -h, --help                 help for apply

Global Flags:
      --color string               set the log color mode, the possible values can be [never always] (default "always")
      --config string              config file of sealer tool (default is $HOME/.sealer.json)
  -d, --debug                      turn on debug mode
      --hide-path                  hide the log path
      --hide-time                  hide the log time
      --log-to-file                write log message to disk
  -q, --quiet                      silence the usage when fail
      --remote-logger-url string   remote logger url, if not empty, will send log to this url
      --task-name string           task name which will embedded in the remote logger header, only valid when --remote-logger-url is set

2022-08-25 14:02:11 [ERROR] [root.go:70] sealer-v0.8.6: Get "https://lb.kubesphere.local:6443/version?timeout=32s": dial tcp: lookup lb.kubesphere.local: no such host

so install prcess break off。

### How to reproduce it (as minimally and precisely as possible)?

```YAML
step1：
      wget sealos 0.8.6 on wsl2,i want to deploy k8s cluster on my 3 vms.(192.168.176.20~22) 
step2:
      make ClusterFile.yaml
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: kubernetes-cluster
spec:
  image: kubernetes:v1.21.5
  ssh:
    passwd: 123456
  hosts:
    - ips: [ 192.168.176.20 ]
      roles: [ master ]
    - ips: [ 192.168.176.21,192.168.176.22 ]
      roles: [ node ]
step3:
   run command on swl2
    # sealer apply -f ./Clusterfile.yaml
```

### Anything else we need to know?

workspace is WSL2
sealer on wsl2
3 vms  are 192.168.176.20~22

### What is the version of Sealer you using?

{"gitVersion":"v0.8.6","gitCommit":"884513e","buildDate":"2022-07-12 02:58:54","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### Other environment you want to tell us?

>>> wsl --list --verbose   
NAME               STATE           VERSION *
CentOS7           Running         2
