### ISSUE TITLE
Optimize: Dynamic variable render

### ISSUE THREAD

**Issue by justadogistaken** [sealerio/sealer#1693]
# Motivation
I feel so puzzled when try to understand the render logic in sealer.
I propose we develop a render manager to deal with all rendering work in sealer.

# Use Cases
I'm trying to list the render-related work here, help me to supply the part what I missed.
## Config Application
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-app/my-SAAS-all-inone:latest
  provider: BAREMETAL
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: mysql-config
spec:
  path: etc/mysql.yaml
  data: |
       mysql-user: root
       mysql-passwd: xxx
```
I feel good with this design, But I guess we can a new filed `application:` after this [work](https://github.com/sealerio/sealer/pull/1658) merged.
But I'm a bit against the way sealer apply the configurations. Refer to [Application config](https://github.com/sealerio/sealer/blob/main/docs/design/global-config.md). Currently sealer will generate corresponding yaml under rootfs/etc/. (I'm considering a better solution)

## Env
This word is too powerful to make people confused.
It could be used to render files in manifests/, etc/, scripts/ and so on.
[Global config & Env in shell plugin](https://github.com/sealerio/sealer/blob/main/docs/design/global-config.md)
I guess we'd better specify the semantics for every kind of env.
I propose:
* [render | env]-[app | scripts | global] to specify the scope of env.

@sealerio/sealer-reviewers Help me review what I missed, plz.

@rambohe-ch Could you help to describe the use cases in openyurt? Which is important for us to make the work better.
