### ISSUE TITLE
combine imageList and imageWithAuth flag

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1840]
## Issue Description

Type: *feature request*

### Describe what feature you want

When building a cluster image, Sealer can specify an imageList file to additionally download the target container image, but the authentication information of different image repositories is inconsistent.

for example:
regular image list is docker format, same registry host have same users: 

{
        "auths": {
                "docker.io": {
                        "auth": "xxxxxx"
                },
                "sea.hub": {
                        "auth": "xxxxxx"
                },
        }
}

image list with auth is adp format, same registry host have different users:

```yaml
- registry: registry.cn-shanghai.aliyuncs.com
  username: user1
  password: pw
  images:
    - registry.cn-shanghai.aliyuncs.com/xxx/xxx1:v1.1
    - registry.cn-shanghai.aliyuncs.com/xxx/xxx2:v1.1
- registry: registry.cn-shanghai.aliyuncs.com
  username: user2
  password: pw
  images:
    - registry.cn-shanghai.aliyuncs.com/xxx/xxx3:v1.1
    - registry.cn-shanghai.aliyuncs.com/xxx/xxx4:v1.1
```
