### ISSUE TITLE
no need to duplicate download container images that already exist in base image

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1881]
### What happen?

here is my Kubefile:

```yaml
FROM registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.22.4
APP dashboard local://dashboard.yaml
LAUNCH ["dashboard"]
```

when i run sealer build , from the log output, i can see sealer still pulling image which is  already exist in base image.

```yaml
Pulling image: docker.io/fanux/lvscare:latest
Pulling image: k8s.gcr.io/kube-apiserver:v1.22.4
Pulling image: k8s.gcr.io/kube-controller-manager:v1.22.4
Pulling image: k8s.gcr.io/kube-scheduler:v1.22.4
Pulling image: k8s.gcr.io/kube-proxy:v1.22.4
Pulling image: k8s.gcr.io/pause:3.5
Pulling image: k8s.gcr.io/etcd:3.5.0-0
Pulling image: k8s.gcr.io/coredns/coredns:v1.8.4
Pulling image: quay.io/tigera/operator:v1.25.3
Pulling image: docker.io/calico/node:v3.22.1
Pulling image: docker.io/calico/pod2daemon-flexvol:v3.22.1
Pulling image: docker.io/calico/cni:v3.22.1
Pulling image: docker.io/calico/kube-controllers:v3.22.1
Pulling image: docker.io/calico/typha:v3.22.1
Pulling image: docker.io/calico/apiserver:v3.22.1
Pulling image: ack-agility-registry.cn-shanghai.cr.aliyuncs.com/sealer/lvscare:v1.1.3-beta.8
Pulling image: docker.io/kubernetesui/dashboard:v2.2.0
```

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:
