### ISSUE TITLE
support taint cluster node through clusterfile

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1889]
## Issue Description

same with configure node label and roles. we also need to support taint cluster node through clusterfile.

```golang

type Host struct {
	IPS   []net.IP `json:"ips,omitempty"`
	Roles []string `json:"roles,omitempty"`
	//overwrite SSH config
	SSH v1.SSH `json:"ssh,omitempty"`
	//overwrite env
	Env []string `json:"env,omitempty"`
	Taints []string `json:"taints,omitempty"`
}
```
```yaml
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  creationTimestamp: null
  name: my-cluster
spec:
  hosts:
  - ips:
    - 172.16.26.187
    roles:
    - node
    taints:
      - key1=value1:NoSchedule
      - key2=value2:NoSchedule-
    ssh: {}
  - ips:
    - 172.16.26.188
    roles:
    - master
    labels:
      fake: labels
    ssh: {}
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.22.4-test
  ssh:
    passwd: testabs
    pk: /root/.ssh/id_rsa
    port: "22"
    user: root
status: {}
```
Type: *feature request*
