### ISSUE TITLE
The image containing the shell plugin does't run

### ISSUE THREAD

**Issue by sunshinejdq** [sealerio/sealer#1961]
### What happen?

When the image containing the shell plugin,sealer apply does not run.
 

### Relevant log output?

```Shell
2023-01-06 15:49:21 [ERROR] [root.go:75] sealer-v0.9.0: failed to ReadDir plugin dir /var/lib/sealer/data/mount/localhost_testshell:1.1/linux_amd64_/plugins: readdirent /var/lib/sealer/data/mount/localhost_testshell:1.1/linux_amd64_/plugins: not a directory
```

### What you expected to happen?

sealer can run the image and run the shell at the specified stage

### How to reproduce it (as minimally and precisely as possible)?

```YAML
[root@master-0 ~]# cat Kubefile 
FROM docker.io/sealerio/kubernetes:v1.22.15
COPY shell.yaml plugins
COPY metrics-server.yaml .
APP metrics local://metrics-server.yaml
LAUNCH ["metrics"]

-----
sealer build -t testshell:1.1 -f Kubefile .
-----

apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: jdq-cluster
spec:
  image: localhost/testshell:1.1 
  hosts:
    - ips: [ 172.30.10.163 ]
      roles: [ master ]
    - ips: [ 172.30.10.53,172.30.10.63,172.30.10.73 ]
      roles: [ node ]  
  ssh:
    passwd: "ka***1"
    user: root
```

### What is the version of Sealer you using?

0.9

### What is your OS environment?

centos 7

### What is the Kernel version?

3.10.0-1160.81.1.el7.x86_64

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:
