### ISSUE TITLE
[Proposal] supporting to config sealer app to enrich the clusterfile's capabilities

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1969]
## Issue Description

Type: *feature request*

### Describe what feature you want

currently ,we can support launching the corresponding app through `ClusterSpec.APPNames`,
Or directly use `ClusterSpec.CMD` to overwrite the app launch cmds.

however, for different types of apps, we have different startup commands and launch files， could we precisely support the configuration of the app at run stage?

so i proposal that we could add `ClusterSpec.Apps` filed as below, for extensibility supporting config the sealer app and enrich the clusterfile's capabilities

1. for app files: We can modify the app file content according to the specified file path, such as `overwrite`,`merge`,`render`.
2. for app launch and delete: We can configure the corresponding launch or delete depending on the type of app, such as `helm`,`kube`,`shell`. At the same time, we can also support the raw launch command line.
 

```yaml
apiVersion: sealer.io/v2
kind: Cluster
metadata:
  name: my-cluster
spec:
  apps:
    - appName: appName
      delete:
        cmds:
          - kubectl delete -f ns.yaml
          - kubectl delete -f nginx.yaml
      launch:
        cmds:
          - kubectl apply -f ns.yaml
          - kubectl apply -f nginx.yaml
        kube:
          - fileNames:
              - ns.yaml
              - nginx.yaml
            namespace: sealer
            action: apply
      appFiles:
        - filePath: ns.yaml
          preProcessor: toSecret|toNamespace
          valueType: 'raw(overwrite),section(merge),args(render)'
          values:
            - key1=value1
            - key2=value2
    - appName: appName
      launch:
        cmds:
          - helm install my-nginx bitnami/nginx
        helm:
          action: install
          chartName: my-nginx
          namespace: sealer
          values:
            - key1=value1
            - key2=value2
      appFiles:
        - filePath: values.yaml
          valueType: raw
          values:
            - key1=value1
            - key2=value2
    - appName: appName
      launch:
        cmds:
          - bash nginx.sh
        shell:
          env:
            - key1=value1
            - key2=value2
          filePath:
            - preinstall.sh
            - nginx.sh
      appFiles:
        - filePath: preinstall.sh
          valueType: raw
          values: |
            kubectl create ns sealer
  hosts:
    - ips:
        - 172.16.83.189
      roles:
        - master
      ssh: { }
  image: 'registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.22.15'
  ssh:
    passwd: Seadent123
    pk: /root/.ssh/id_rsa
    port: '22'
    user: root
```
