### ISSUE TITLE
[Proposal]Support sealer upgrade

### ISSUE THREAD

**Issue by wizardlyk** [sealerio/sealer#2018]
## Issue Description

Type: *feature request*

### Describe what feature you want

Upgrade kubernetes cluster by using sealer upgrade --flags

#### Build an upgrade image
Kubefile:
```
FROM docker.io/sealerio/kubernetes:v1.20.4
COPY kube-upgrade.tar.gz .
CMDS ["tar zxvf kube-upgrade.tar.gz"]
```

build command:
```
sealer build -f Kubefile -t upgrade-kubernetes:v1.22.15 .
```
upgrade image contains：
1. New version k8s images：kube-apiserver，kube-controller-manager，kube-scheduler，kube-proxy，pause，etcd，etc.；
2. New version k8s bin/rpm：kubeadm，kubectl，kubelet，etc.；
3. Upgrade shell & binary tool。

#### Sealer upgrade --flags
1. Distribute files & configs to all cluster nodes；
2. Pre-check cluster；
3. Execute the upgrade command through sealer Plugin API；
4. Post-check cluster，rollback after upgrade failure。

upgrade command:
```
sealer upgrade upgrade-kubernetes:v1.22.15
```

plugin API:
```
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: upgrade_host
spec:
  type: SHELL
  action: upgrade-host
  scope: master | node
  data: |
    set -x
    trident upgradev2 --pkg-url=/root/kube.tar.gz
```
