### ISSUE TITLE
sealer upgrade failed

### ISSUE THREAD

**Issue by yuexian1234** [sealerio/sealer#2114]
### What happen?

1. sealer -d  upgrade kubernetes:v1.21.5 --cluster my-cluster
2. find errors sea.hub:5000/coredns:v1.8.0 not found
3. by sealer inspect ,find imageList
4. edit the coredns image version to 1.7.0 from imageList file
5. retry " sealer -d  upgrade kubernetes:v1.21.5 --cluster my-cluster"
6. find error,also "sea.hub:5000/coredns:v1.8.0 not found"

![image](https://user-images.githubusercontent.com/14341344/225266975-628ce022-54a1-478d-85db-4365bde65806.png)
![image](https://user-images.githubusercontent.com/14341344/225267002-33e08d28-d508-4c4e-a085-a737add9a15b.png)

### Relevant log output?

```Shell
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade/version] You have chosen to change the cluster version to "v1.21.5"
[upgrade/versions] Cluster version: v1.20.10
[upgrade/versions] kubeadm version: v1.21.5
[upgrade/prepull] Pulling images required for setting up a Kubernetes cluster
[upgrade/prepull] This might take a minute or two, depending on the speed of your internet connection
[upgrade/prepull] You can also perform this action in beforehand using 'kubeadm config images pull'
[preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image sea.hub:5000/coredns:v1.8.0: output: Error response from daemon: manifest for sea.hub:5000/coredns:v1.8.0 not found: manifest unknown: manifest unknown
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
2023-03-15 09:09:39 [DEBUG] [sshcmd.go:114] failed to execute command(kubeadm upgrade apply v1.21.5 -y) on host(192.168.122.125): error(failed to execute command(kubeadm upgrade apply v1.21.5 -y) on host(192.168.122.125): error(exit status 2))
```

### What you expected to happen?

upgrade successful

### How to reproduce it (as minimally and precisely as possible)?

```YAML
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  annotations:
    ClusterfileName: /root/.sealer/my-cluster/Clusterfile
  creationTimestamp: null
  name: my-cluster
spec:
  hosts:
  - ips:
    - 192.168.122.125
    roles:
    - master
    ssh: {}
  image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.20.10
  ssh:
    encrypted: true
    pk: /root/.ssh/id_rsa
    port: "22"
    user: root
```

### What is the version of Sealer you using?

{"gitVersion":"v0.8.6","gitCommit":"884513e","buildDate":"2022-07-12 02:58:54","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

NAME="Debian GNU/Linux" VERSION_ID="11"

### What is the Kernel version?

Linux debian8 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

### Other environment you want to tell us?

# current version

root@debian8:~# kubectl  get node
NAME      STATUS                     ROLES                  AGE   VERSION
debian8   Ready,SchedulingDisabled   control-plane,master   9d    v1.20.10
