### ISSUE TITLE
Cluster file taints value is slow

### ISSUE THREAD

**Issue by sunshinejdq** [sealerio/sealer#2163]
### What happen?

I want to remove the master node's taints value noschedule, I write taints: node.kubernetes.io/not-ready:NoSchedule- in the cluster file. I have mysql in my image, and the taints value is not removed until my mysql status becomes ready.

### What you expected to happen?

 I want this value to take effect before mysql is deployed.

### How to reproduce it (as minimally and precisely as possible)?

```YAML
Kubefile:
FROM docker.io/sealerio/kubernetes:v1-22-15-sealerio-2
APP localpv local://localpv.yaml
APP mysql local://mysql.yaml
LAUNCH ["calico","localpv","mysql"]
---
sealer build -f Kubefile -t local_mysql:v1.5 .
---
Clusterfile:
Version: sealer.cloud/v2
kind: Cluster
metadata:
  name: my-cluster
spec:
  hosts:
    - ips:
        - 192.168.20.170
      roles:
        - master
      taints:
        - node.kubernetes.io/not-ready:NoSchedule-
    - ips:
        - 192.168.20.171
      roles:
        - node
  image: localhost/local_mysql:v1.5
  ssh:
    passwd: XXXX
---
mysql.yaml
...
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mysql
                    app.kubernetes.io/instance: my-mysql
                namespaces:
                  - "mysql-system"
                topologyKey: kubernetes.io/hostname
...
```

### What is the version of Sealer you using?

v0.9.2

### What is your OS environment?

CentOS Linux release 7.9.2009 (Core)

### What is the Kernel version?

Linux master0 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:
