### ISSUE TITLE
[feature] make cluster env more easy to understand

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#2174]
## Issue Description

Background : 

as we know , we using `cluster.env` do some customized  configuration .

```yaml
[root@iZbp133pwc8drrt7ra1mkhZ ~]# cat .sealer/Clusterfile 
apiVersion: sealer.io/v2
kind: Cluster
metadata:
  name: my-cluster
spec:
  containerRuntime: {}
  env:
  - RegistryDomain=sea.hub
  - RegistryPort=5000
  - RegistryURL=sea.hub:5000
```

when dealing with this filed internally, sealer will convert string slice to map `map[string]interface{}`.
for examples:  some argument is list, like: `CertSANS=127.0.0.1 CertSANS=localhost`,  sealer will  convert it to `{CertSANS:[127.0.0.1, localhost]}`.

this logic is against with conventional understanding. 

so i proposal that if the key is the same, thats value will be overwritten by latest one, and also convert string slice to `map[string]string` which is sensitive for shell bash. 
	
FYI : https://github.com/sealerio/sealer/blob/006e1db5f14e461fc0ca1990c9433cf6760f1b9e/utils/strings/strings.go#L162
Type: *feature request*
