### ISSUE TITLE
host type plugin is not working 

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#2192]
### What happen?

below is my plugin, for  `host type` plugin,  if not set `scope: master`, it will not work. 

so maybe we should add default scope if user do not specify this filed .

```
apiVersion: sealer.io/v2
kind: Plugin
metadata:
  name: pre_init_host 
spec:
  type: SHELL
  action: pre-init-host
  data: |
    echo "i am pre init host plugin"
```

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:
