### ISSUE TITLE
Calico is not running and application env don't take effect

### ISSUE THREAD

**Issue by sunshinejdq** [sealerio/sealer#2230]
### What happen?

After using the image with calico, it was found that calico is not running.

I don't use the clusterfile , use run command, Calico still doesn't run.

`sealer run docker.io/sealerio/kubernetes:v1-22-15-sealerio-2 --masters 192.168.10.170 --nodes 192.168.10.171 --passwd  'xxx'`

container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized                      

### What you expected to happen?

calico is running

### How to reproduce it (as minimally and precisely as possible)?

```YAML
Kubefile:
FROM docker.io/sealerio/kubernetes:v1-22-15-sealerio-2
APP localpv local://localpv.yaml
APP mysql local://mysql.yaml
LAUNCH ["calico","localpv","mysql"]

Clusterfile:
apiVersion: sealer.io/v2
kind: Application
metadata:
  name: my-apps
spec:
  launchApps:
    - calico
    - localpv
    - mysql
  configs:
    - name: mysql
      files:
        - path: mysql.yaml
          strategy: "overwrite"
          data: |
            data:
              mysql-root-password: "amRxKysyMDIwCg=="
---
Version: sealer.cloud/v2
kind: Cluster
metadata:
  name: my-cluster
spec:
  #env:
    #- PodCIDR=18.16.0.0/16
    #- SvcCIDR=10.18.0.0/16
  hosts:
    - ips:
        - 192.168.20.170
      roles:
        - master
    - ips:
        - 192.168.20.171
      roles:
        - node
  image: localhost/app_env:1.0
  ssh:
    passwd: psc@2021
---
mysql.yaml
...
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-mysql
  namespace: mysql-system
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: my-mysql
type: Opaque
data:
  mysql-root-password: "RWZuaWJiQzFaeQ=="
  mysql-password: "dnR0TDlSaG1EbQ=="
  mysql-replication-password: "NWd1MUxrU09Kdw=="
```

### What is the version of Sealer you using?

v0.10.0

### What is your OS environment?

CentOS Linux release 7.9.2009 (Core)

### What is the Kernel version?

Linux master0 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:
