### ISSUE TITLE
Application config overwrite doesn't work

### ISSUE THREAD

**Issue by JJGGu** [sealerio/sealer#2297]
### What happen?

I use application api to overwrite my helm values.yaml，and use sealer apply command to deploy the cluster, but it does't work. I'm not sure if i use the application api incorrectly or it's a bug. Besides, I want to make sure the "overwrite" option means overwrite all content of specified file or overwrite the value of the key.
![image](https://github.com/sealerio/sealer/assets/24667092/208709d6-53e2-471f-a03e-128c6d02560f)

### How to reproduce it (as minimally and precisely as possible)?

```YAML
Sealer version: 0.9.3

Kubefile：
FROM ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/ackdistro:v1-22-15-ack-10
APP nginx local://nginx/
LAUNCH ["nginx"]


Clusterfile:
apiVersion: sealer.io/v2
kind: Application
metadata:
  name: my-apps
spec:
  launchApps:
    - nginx
  configs:
    - name: nginx
      files:
        - path: values.yaml
          strategy: "overwrite"
          data: |
            replicaCount: 2
---
apiVersion: sealer.io/v2
kind: Cluster
metadata:
  name: my-cluster
spec:
  hosts:
    - ips:
        # input master ips, for example:
        # - 10.0.1.1
        # - 10.0.1.2
        - 192.168.0.203
      roles:
        - master
    - ips:
        # input worker ips, for example:
        # - 10.0.1.3
        # - 10.0.1.4
        - 192.168.0.202
      roles:
        - node
  image: localhost/image:v1
  ssh:
    # The master and worker password is same.
    passwd: asdf123-
```

### What is the version of Sealer you using?

0.9.3

### What is your OS environment?

centos7.9

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:
